### ISSUE TITLE
Change <title>Healthcare Services &amp; Solutions</title>

### ISSUE THREAD

**Issue by JosephCosta** [RevHealth/hss#1]
to: <title>Foster Services &amp; Solutions</title>

**Comment by rfoost** [comment]
I just made the commit. Please review change.

**Comment by JosephCosta** [comment]
Looks good...push to Dev

**Comment by JosephCosta** [comment]
Rollback: Should be Healthcare

**Comment by johndougherty68** [comment]
Changed back to Healthcare

**Comment by JosephCosta** [comment]
Looks Good..I'm pushing to Stage
